# Mod
modId=voxyrenderfilter
modName=VoxyRenderFilter
modDescription=Voxy cache coverage map, region-only LOD rendering filter and region cache deletion.
modAuthor=Whisperlyric
modVersion=0.1.2
modLicense=LGPL 3.0

# Dependencies
minecraftVersion=26.1.2
fabricVersion=0.19.3
fabricApiVersion=0.155.2+26.1.2
mixinVersion=0.12.5+mixin.0.8.5

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
